name: 'Cherry Pick PR for label'
description: 'Opens a new PR based off a labelled one'
inputs:
  github-token:
    description: 'GitHub token with read and write access on the project.'
    required: true
runs:
  using: 'node12'
  main: 'index.js'